name: publish-beta

on: workflow_dispatch

jobs:
  publish-beta:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm install
      - run: npm run beta
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
